# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: DanBearl # jekyll-seo-tag > Owners twitter username
author: Dan Bearl # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Dan Bearl # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/DanBearl
    - https://www.linkedin.com/in/dan-bearl-2440954
    - https://github.com/danbearl

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/New_York # Timezone for blog posts and alike
#destination: /var/www/html/

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Security musings for the masses" # The post list page content
    feature_text: |
      ## Friggin' Security Blog
#    feature_image: "https://unsplash.it/1300/400?image=1067"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Friggin' Security" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/placeholder-logo.png" # Site logo, also used in jekyll-seo-tag
description: "Friggin' Security is a blog about IT security intended for a non-technical audience. Everyone uses information technology, and everyone deserves to have the knowledge and tools to use it safely." # Site description and default description, also used in jekyll-seo-tag
url: "http://www.frigginsec.com" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/daviddarnes/alembic"
email: "dan.bearl@gmail.com"
disqus: "frigginsec"
#avatarurl: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Blog: /blog/

navigation_footer:
  Words by Dan Bearl, built with Jekyll and Alembic: https://www.danielbearl.com

social_links:
  Twitter: https://twitter.com/danbearl
  LinkedIn: https://www.linkedin.com/in/dan-bearl-2440954
  GitHub: https://github.com/danbearl
  link: https://www.danielbearl.com
